using UnityEngine;

public class FMODEvent : MonoBehaviour
{
    //[SerializeField, FMODUnity.EventReference] private string eventPath; // This is the path to the event in FMOD. The "EventReference" attribute created the cool FMOD menu in the Inspector.
    
    private FMOD.Studio.EventInstance eventInstance; // This stores the event instance (a perfect copy of the event in FMOD).
    public FMODUnity.EventReference eventPath;

    private void Start()
    {
        eventInstance = FMODUnity.RuntimeManager.CreateInstance(eventPath); // Create an instance of the event.
        FMODUnity.RuntimeManager.AttachInstanceToGameObject(eventInstance, transform, GetComponent<Rigidbody2D>()); // Attach the instance of the event to the gameObject's transform and rigidbody.
    }

    public void PlayEvent()
    {
        eventInstance.start(); // Play the sounds inside the event in FMOD.
    }

    public void StopEvent()
    {
        eventInstance.stop(FMOD.Studio.STOP_MODE.ALLOWFADEOUT); // Stop any sounds generated by this event (while allowing fades).
    }
}
